---
title: "Mini-Project 2"
author: "Dianne Caravela, Neyda Carrillo, Carmen Canedo"
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---

```{r, message=FALSE}
library(tidyverse)
library(devtools)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```
> Word count: 'r wordcountaddin::word_count()'

###Committee Party Affiliation 

```{r, message=FALSE}
party_cmteREP <- committees %>%
  filter(cmte_state == "AZ") %>%
  filter(cmte_party_affiliation == "REP") %>%
  group_by(cmte_party_affiliation) %>%
  select(cmte_id) 
party_cmteREP
```

```{r, message=FALSE}
party_cmteDEM <- committees %>%
  filter(cmte_state == "AZ") %>%
  filter(cmte_party_affiliation == "DEM") %>%
  group_by(cmte_party_affiliation) %>%
  select(cmte_id) 
party_cmteDEM
```


###Committee Contribution  

```{r, message=FALSE}
trans_amt <- contributions %>%
  select(cmte_id, transaction_amt)
trans_amt
```

###Committe Expenditure

```{r, message=FALSE}
REPcmte_expenditure <- inner_join(party_cmteREP, trans_amt)
REPcmte_expenditure
```

```{r, message=FALSE}
DEMcmte_expenditure <- inner_join(party_cmteDEM, trans_amt)
DEMcmte_expenditure
```

```{r}

```

